# Generated by Django 5.1.2 on 2024-10-17 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shiftschedule", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guard",
            name="availability_day",
        ),
        migrations.RemoveField(
            model_name="guard",
            name="availability_night",
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_or_night",
                    models.CharField(
                        choices=[("day", "Day"), ("night", "Night")], max_length=5
                    ),
                ),
                ("hours", models.CharField(max_length=100)),
                (
                    "guard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="shiftschedule.guard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_or_night",
                    models.CharField(
                        choices=[("day", "Day"), ("night", "Night")], max_length=5
                    ),
                ),
                ("shift_start", models.DateTimeField()),
                ("shift_end", models.DateTimeField()),
                (
                    "guard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="shiftschedule.guard",
                    ),
                ),
            ],
        ),
    ]
