# Generated by Django 5.1.2 on 2024-10-19 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shiftschedule", "0002_remove_guard_availability_day_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together={("guard", "day_or_night")},
        ),
        migrations.AddField(
            model_name="availability",
            name="available_hours",
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="availability",
            name="guard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shiftschedule.guard"
            ),
        ),
        migrations.RemoveField(
            model_name="availability",
            name="hours",
        ),
    ]
