# Generated by Django 5.1.2 on 2024-10-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shiftschedule", "0004_guard_available_hours_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guard",
            name="available_hours_day",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="guard",
            name="available_hours_night",
            field=models.JSONField(default=list),
        ),
    ]
