# Generated by Django 5.1.2 on 2024-10-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shiftschedule", "0006_remove_schedule_guard_remove_shift_guard_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guard",
            name="available_hours_day",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="guard",
            name="available_hours_night",
            field=models.CharField(default="", max_length=255),
        ),
    ]
