# Generated by Django 5.1.2 on 2024-10-22 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shiftschedule", "0007_alter_guard_available_hours_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuardShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "guard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shiftschedule.guard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "shift_type",
                    models.CharField(
                        choices=[("day", "Day"), ("night", "Night")], max_length=5
                    ),
                ),
                (
                    "guards",
                    models.ManyToManyField(
                        through="shiftschedule.GuardShift", to="shiftschedule.guard"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="guardshift",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shiftschedule.schedule"
            ),
        ),
    ]
