# Generated by Django 5.1.2 on 2024-10-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shiftschedule", "0009_guard_total_hours"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guard",
            old_name="total_hours",
            new_name="available_hours_amount",
        ),
        migrations.AddField(
            model_name="guard",
            name="last_location_in_solution",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="guard",
            name="remaining_hours",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="guard",
            name="sequence_number",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="guard",
            name="total_hours_guarded",
            field=models.IntegerField(default=0),
        ),
    ]
