# Generated by Django 5.1.2 on 2024-10-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shiftschedule",
            "0010_rename_total_hours_guard_available_hours_amount_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="guard",
            old_name="available_hours_amount",
            new_name="available_hours_amount_day",
        ),
        migrations.AddField(
            model_name="guard",
            name="available_hours_amount_night",
            field=models.IntegerField(default=0),
        ),
    ]
