# Generated by Django 5.1.2 on 2024-10-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shiftschedule",
            "0011_rename_available_hours_amount_guard_available_hours_amount_day_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="guard",
            old_name="remaining_hours",
            new_name="remaining_hours_day",
        ),
        migrations.AddField(
            model_name="guard",
            name="remaining_hours_night",
            field=models.IntegerField(default=0),
        ),
    ]
