# Generated by Django 5.1.2 on 2024-10-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shiftschedule", "0014_remove_guard_available_hours_amount_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guard",
            name="check_available_hours_day",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="guard",
            name="check_available_hours_night",
            field=models.CharField(default="", max_length=255),
        ),
    ]
