# Generated by Django 5.1.2 on 2024-10-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shiftschedule", "0015_guard_check_available_hours_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guard",
            name="hours_of_shift",
            field=models.CharField(default="", max_length=255),
        ),
    ]
