# Generated by Django 5.1.2 on 2024-11-01 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shiftschedule", "0016_guard_hours_of_shift"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guard",
            name="hours_of_shift",
        ),
    ]
