# Generated by Django 5.1.2 on 2024-11-01 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shiftschedule", "0018_alter_guard_available_hours_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guard",
            name="check_available_hours_day",
        ),
        migrations.RemoveField(
            model_name="guard",
            name="check_available_hours_night",
        ),
    ]
