# Generated by Django 5.1.2 on 2024-11-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shiftschedule", "0019_remove_guard_check_available_hours_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guard",
            name="before_available_hours_day",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="guard",
            name="before_available_hours_night",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
