# Generated by Django 5.1.2 on 2024-11-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shiftschedule", "0020_guard_before_available_hours_day_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guard",
            old_name="available_hours_day",
            new_name="available_shifts_day",
        ),
        migrations.RenameField(
            model_name="guard",
            old_name="available_hours_night",
            new_name="available_shifts_night",
        ),
        migrations.RenameField(
            model_name="guard",
            old_name="before_available_hours_day",
            new_name="unavailable_hours_day",
        ),
        migrations.RenameField(
            model_name="guard",
            old_name="before_available_hours_night",
            new_name="unavailable_hours_night",
        ),
    ]
